config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  resources :tasks, shallow: true do
  	post 'start'
  	post 'finish'
    post 'cancel'
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  #include ActiveModel::Validations
  belongs_to :user

  validates :user_id,     presence: true
  validates :name,        presence: true
  validates :description, presence: true, length: { minimum: 2, maximum: 1000 }
  validates :state,       presence: true, inclusion: { in: ['new', 'started', 'finished'] }

  def start_task
    update_attributes(state: 'started')
  end

  def finish_task
    update_attributes(state: 'finished')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :tasks, foreign_key: 'user_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_task_id, only: [:start, :finish]
  before_action :load_task, only: [:show, :edit, :update, :destroy]

  respond_to :js, only: [:start, :finish, :cancel]
  respond_to :html

  def index
    respond_with(@tasks = Task.all.order('created_at'))
  end

  def show
    respond_with @task
  end

  def new
    respond_with(@task = Task.new)
  end

  def edit
  end

  def create
    respond_with(@task = Task.create(task_params))
  end

  def update
    @task.update(task_params)
    respond_with @task
  end

  def destroy
    @task.destroy if @task.user_id == current_user.id
    respond_with @task
  end

  def start
    @task.start_task
  end

  def finish
    @task.finish_task
  end

  private

  def load_task
    @task = Task.find(params[:id])
  end

  def load_task_id
    @task = Task.find(params[:task_id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :state).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Taskmanager"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"Taskmanager
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            - if current_user
              li= link_to "Новая задача", new_task_path
              li= link_to current_user.email
              li= link_to "Выйти", destroy_user_session_path, method: :delete
            - else
              li= link_to "Войти", new_user_session_path
              li= link_to "Регистрация", new_user_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

      footer
        p &copy; Taskmanager 2015

app/views/tasks/_form.html.slim
div
  = f.label :name, "Наименование:"
  = f.text_field :name
div
  = f.label :description, "Описание:"
  = f.text_field :description

app/views/tasks/_task.html.slim
td
  - if current_user && current_user.id == task.user_id
    i Моя задача
  - else
    = task.user.email
td = task.created_at.strftime("%d.%m.%y")
td = link_to (task.name), task_path(task)
td = task.state
td
  - if current_user && current_user.id == task.user_id
    - if task.state == 'new'
      = link_to "Пуск задачи!", task_start_path(task), method: :post, remote: true, class: 'btn btn-default btn-xs start-task-link'
    - else
      - if task.state == 'started'
        = link_to("Завершить задачу", task_finish_path(task), method: :post, remote: true, class: 'btn btn-primary btn-xs start-task-link')
      - else
        = link_to("На доработку.", task_start_path(task), method: :post, remote: true, class: 'btn btn-danger btn-xs start-task-link')

app/views/tasks/edit.html.slim
h1 Редактирование задачи:
= form_for @task do |f|
  = render partial: "form", locals: { f: f }
  = f.submit "Изменить задачу", class: 'btn btn-success btn-sm'

app/views/tasks/finish.js.erb
$("#task_<%= @task.id %>").replaceWith("<tr id='task_<%= @task.id %>'>" + '<%= j render 'task', task: @task %>' + "</tr>");

app/views/tasks/index.html.slim
- unless @tasks.empty?
  div class="panel panel-default"
    div class="panel-heading" Задачи:
    table class="table"
      tr
        th Создал:
        th Дата:
        th Задача:
        th Состояние:
        th Контроль:
      - @tasks.each do |task|
        tr id="task_#{task.id}"
          = render 'task', task: task
- else
  h4 Задач пока нет!

app/views/tasks/new.html.slim
h1 Новая задача:
= form_for @task do |f|
  = render partial: "form", locals: { f: f }
  .task-errors
  br
    = f.submit "Добавить задачу", class: 'btn btn-success btn-sm'

app/views/tasks/show.html.slim
h2
  = @task.name
br
  - if current_user && current_user.id == @task.user_id
    = link_to "Редактировать?", edit_task_path(@task)
    i &nbsp; или &nbsp;
    = link_to "Удалить?", @task, method: :delete, data: {confirm: "Подтверждение удаления"}
div
  i Описание:&nbsp;
  = @task.description
div
  i Состояние:&nbsp;
  = @task.state
div
  i Создал:
  = @task.user.email

app/views/tasks/start.js.erb
$("#task_<%= @task.id %>").replaceWith("<tr id='task_<%= @task.id %>'>" + '<%= j render 'task', task: @task %>' + "</tr>");